worker_processes 1;

events {}

http {
    upstream app_backend {
        server app:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 8080;

        location /stub_status {
            stub_status;
            allow all;
        }
    }
}

