name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Testowanie aplikacji
    runs-on: ubuntu-latest
    
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalacja zależności
        run: |
          pip install -r requirements.txt

      - name: Sprawdzanie jakości kodu (Linting)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Uruchomienie testów (Pytest)
        env:
          PYTHONPATH: .
        run: |
          pytest
